### ISSUE TITLE
Kalender

### ISSUE THREAD

**Issue by Huber1** [dev-redcube/betterHM#100]
### Beschreibe dein Feature

Anstatt der SemesterStatus Karte, eine Kalender Karte und nen gescheiten kalender
kann in zukunft erweitert werden für andere events
Dabei gleich laden des kalenders auslagern zu service

### In wie fern profitiert das Projekt von diesem Feature?

kann erweitert werden für andere events + übersichtlicher

### Weitere Informationen

z.b. https://pub.dev/packages/syncfusion_flutter_calendar oder https://pub.dev/packages/calendar_view

### Ich kann dieses Feature selbst implementieren / mithelfen bei der Umsetzung

Ja

**Comment by Huber1** [comment]
wird wahrscheinlich ne eigenentwicklung, da die beiden libraries rausfallen:
- syncfusion: probleme mit lizenz, support nervt dauernt mit emails
- calendar_view: kein dark mode, kann nicht direkt verwendet werden
Eventuell ein fork von calendar_view, noch nicht endgültig entschieden

**Comment by Huber1** [comment]
Eine eigene Kalenderkomponente ist in arbeit und wird dann als dependency eingebettet

**Comment by Huber1** [comment]
Package wird vsl nächste Woche fertig und es kann angefangen werden, diese zu implementieren.

Weiteres Vorgehen:
- Implementierung eines Kalenderservices (abfragen von Server)
- Datenbankschema zum Speichern der Events
- (später) Service zum hinzufügen des Kalenders zum Systemkalender

**Comment by adriangeorgimmel** [comment]
mögliche Library nutzbar für das parsen einer ical Datei
https://pub.dev/packages/icalendar_parser

**Comment by Huber1** [comment]
- Dieses Feature ist jetzt Teil von #110
