### ISSUE TITLE
Eigenes Backend

### ISSUE THREAD

**Issue by Huber1** [dev-redcube/betterHM#96]
Wir brauchen auf lange Zeit ein eigenes Backend.

Aktuell ist ein Problem, dass die MVG Api extrem langsam ist. Mit einem eigenen Backend könnten die Anfragen gecached werden (1,2, oder sogar 5 minuten). Damit wären die langen Wartezeiten für die meisten Nutzer nicht mehr vorhanden

Gleichzeitig könnten die Anfragen auf Drittanbieter-APIs deutlich reduziert werden

**Comment by adriangeorgimmel** [comment]
ich schau mal ob der cache über Cloudflare realisierbar ist

**Comment by Huber1** [comment]
gerne, das würde aber nur einen Teil Lösen. Früher oder später brauchen wir sowieso ein Backend, mindestens für Benachrichtigungen

**Comment by Huber1** [comment]
https://github.com/dev-redcube/betterhm-backend
